# 4.5 선형대수

In [1]:
import numpy as np

In [2]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])

In [3]:
y=np.array([[6.,23,],[-1,7],[8,9]])

In [4]:
print(x);print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [5]:
x.dot(y) #x%*%y (2X3)X(3X2), dot은 행렬의 곱셈을 해주는 함수

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x,np.ones(3)) #(2X3)X(3X1)

array([ 6., 15.])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
from numpy.linalg import inv,qr #numpy.linalg은 행렬의 분할 역행렬,행렬식 포함

In [9]:
X=np.random.randn(5,5)

In [10]:
X

array([[ 0.25286875,  1.31635984,  0.24718972, -0.14807216, -1.41798968],
       [-0.01091769, -0.43356935, -0.78596039,  0.7668239 ,  0.73112262],
       [ 2.01064677, -0.11322008,  0.19384068,  0.5300807 , -0.78400454],
       [-0.0572281 ,  0.79255239, -0.23680832,  0.81792947,  1.75191068],
       [ 0.2945874 ,  0.41443275,  0.17154629,  0.15997911,  1.14003247]])

In [11]:
mat=X.T.dot(X) #X^2

In [12]:
inv(mat)

array([[  7.87418934,   3.91984804, -17.36646866, -17.38860333,
          3.46774316],
       [  3.91984804,   2.44511116,  -9.24330419,  -8.94636275,
          1.714557  ],
       [-17.36646866,  -9.24330419,  41.22308398,  39.44835643,
         -7.45093429],
       [-17.38860333,  -8.94636275,  39.44835643,  39.75812559,
         -7.83339876],
       [  3.46774316,   1.714557  ,  -7.45093429,  -7.83339876,
          1.73952772]])

In [13]:
mat.dot(inv(mat)) #mat의 역행렬 X mat 행렬

array([[ 1.00000000e+00, -4.44089210e-16, -1.77635684e-15,
         3.55271368e-15, -4.44089210e-16],
       [-2.33146835e-15,  1.00000000e+00,  3.33066907e-15,
         2.22044605e-16, -9.99200722e-16],
       [-4.44089210e-15, -8.88178420e-16,  1.00000000e+00,
         5.32907052e-15, -1.33226763e-15],
       [-8.88178420e-16, -1.77635684e-15, -1.77635684e-15,
         1.00000000e+00, -1.77635684e-15],
       [ 0.00000000e+00,  3.55271368e-15, -2.84217094e-14,
         0.00000000e+00,  1.00000000e+00]])

In [14]:
q,r=qr(mat) #QR분해라고 한다 나도 잘모름?

https://ko.wikipedia.org/wiki/QR_분해 #이럴땐 위키!

In [15]:
r

array([[-4.67757045, -0.44889915, -0.90191514, -0.46832096,  4.00489327],
       [ 0.        , -2.76669465, -0.64059124,  0.1092257 ,  0.48953939],
       [ 0.        ,  0.        , -1.4655388 ,  2.71709929,  6.3312588 ],
       [ 0.        ,  0.        ,  0.        ,  0.5774009 ,  2.97385139],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.08610794]])

In [16]:
q

array([[-0.89722198,  0.07809952,  0.15985124,  0.27235763, -0.29860021],
       [-0.0399106 , -0.98152587,  0.0935691 , -0.06680018, -0.14763697],
       [-0.11222066, -0.17249751, -0.4027209 ,  0.61954518,  0.64158458],
       [-0.2181281 , -0.01056555,  0.61840317, -0.33898634,  0.67451781],
       [ 0.36500208,  0.0253064 ,  0.64891124,  0.65008544, -0.14978714]])

## 자주 사용하는 numpy.linalg함수

$numpy.diag$

$numpy.dot$

$numpy.trace$

$numpy.linalg.det$

numpy.linalg.eig

$numpy.linalg.inv$

numpy.linalg.pinv

numpy.linalg.qr

numpy.linalg.svd

$numpy.linalg.solve$ #Ax=b 를 만족하는 x구함

$numpy.linalg.lstsq$ #y=xb를 만족하는 최소제곱해를 구함

In [17]:
x=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

In [18]:
y=np.array([[4.,5.,6.],[7.,8.,9.],[1.,2.,3.]])

In [19]:
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
y

array([[4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.]])

문제!

1.행렬 x의 대각선 원소를 반환하시오

2.행렬 x X y를 구하시오

3.행렬 x의 대각선 원소의 합을 구하시오(trace이용)

4.det(y)를 구하시오

array([1., 5., 9.])

array([[ 21.,  27.,  33.],
       [ 57.,  72.,  87.],
       [ 93., 117., 141.]])

15.0

6.66133814775094e-16

# 4.6 난수 생성

In [25]:
samples =np.random.normal(size=(4,4))

In [26]:
samples

array([[ 1.21449878,  0.33259825, -0.95704555, -0.60089402],
       [ 0.91535964,  1.154005  , -1.03376625, -0.6499104 ],
       [ 1.273032  ,  0.0944535 , -0.90580737,  0.14998781],
       [ 0.69106257,  1.23434592, -1.43114769, -0.43179376]])

In [27]:
from random import normalvariate

In [28]:
N=1000000

In [29]:
%timeit samples =[normalvariate(0,1) for _ in range(N)]

4.46 s ± 603 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
%timeit np.random.normal(size=N) #위에 있는 파이선 내장 모듈보다 속도가 빠름을 알 수 있음

194 ms ± 32.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 4.7 계단 오르내리기 예제

In [31]:
import random
position =0
walk =[position]
steps =1000
for i in range(steps):
    step =1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [32]:
nsteps=1000

In [33]:
draws= np.random.randint(0,2,size=nsteps)

In [34]:
steps=np.where(draws>0,1,-1)

In [35]:
walk=steps.cumsum()

In [36]:
walk.min()

-1

In [37]:
walk.max()

68

In [38]:
(np.abs(walk)>=10).argmax()

75

## 4.7.1 계단 한번에 오르내리기 시뮬레이션하기

In [39]:
nwalks=5000

In [40]:
nsteps=1000

In [41]:
draws= np.random.randint(0,2, size=(nwalks, nsteps))

In [42]:
draws

array([[1, 0, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 0]])

In [43]:
steps =np.where(draws>0,1,-1)

In [44]:
walks = steps.cumsum(1)

In [45]:
walks

array([[  1,   0,  -1, ..., -20, -19, -20],
       [ -1,  -2,  -1, ..., -22, -21, -20],
       [  1,   2,   3, ...,  20,  19,  18],
       ...,
       [  1,   2,   1, ...,  58,  59,  58],
       [  1,   2,   1, ...,  36,  37,  38],
       [  1,   0,  -1, ..., -22, -21, -22]], dtype=int32)

In [46]:
walk.max()

68

In [47]:
walk.min()

-1

In [48]:
hits30 =(np.abs(walks)>=30).any(1)

In [49]:
hits30

array([ True, False,  True, ...,  True,  True,  True])

In [50]:
hits30.sum()

3361

In [51]:
crossing_times= (np.abs(walks[hits30])>=30).argmax(1)

In [52]:
crossing_times.mean()

504.86730139839335

In [53]:
steps= np.random.normal(loc=0,scale=0.25,size=(nwalks,nsteps))

In [54]:
steps

array([[ 0.18133876, -0.19501663,  0.25939138, ...,  0.46399828,
         0.0141341 ,  0.08777334],
       [-0.18974595, -0.15910886,  0.01057835, ..., -0.11091222,
         0.12244043,  0.11250235],
       [ 0.01573796,  0.1950755 , -0.11333786, ...,  0.0356287 ,
        -0.27088677, -0.10639957],
       ...,
       [ 0.24821691, -0.02208584, -0.07766161, ..., -0.09024491,
        -0.06592528, -0.47119648],
       [ 0.303796  , -0.02692399, -0.4032154 , ..., -0.70419455,
        -0.13522352, -0.04875336],
       [ 0.2705364 , -0.33116589, -0.19964717, ...,  0.06391516,
        -0.07505308,  0.08985524]])